language: clojure
lein: lein2
before_install:
- echo y | sudo lein2 upgrade
- lein2 with-profile +travis install
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: SMi3LbjJEab/9y1QYmpjqO/Q3R1U7wu3B89QRLa9O9dV0q2jVGI8AsvV27hAUlpm+/A+svlQqo+X/Pe+PUMshns+iv0UJUvSFGoN1H7ckHsz+jrP19dVbQT3dXgaGdqpT4U3qAZewLeElRynClpLfE6Tp7GtZj4sjSeCTjVH9bc=
